### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by gfredericks** [achim/multiset#3]
Would be nice to have a fixed non-snapshot release of this.

I just deployed `[com.gfredericks.forks.org.clojars.achim/multiset "0.1.0-5ee7264"]` in the meantime.

**Comment by tsdh** [comment]
Oh, yes, please.

**Comment by achim** [comment]
I finally got around to doing this – sorry for the delay!

**Comment by tsdh** [comment]
Thanks!  Although my need for multisets vanished due to a better algorithm. ;-)

Anyway, the next possibility of using them comes for sure, and then it's good to have a current release.
