### ISSUE TITLE
Calling vec on an empty multiset throws a null pointer exception

### ISSUE THREAD

**Issue by scotfrey** [achim/multiset#5]
In the repl, if I do:
```clojure
(require '[multiset.core :as ms])
(vec (ms/multiset))
```
it gives me this error:
`NullPointerException   multiset.core.MultiSet (core.clj:73)`

In a project I'm working on, it does this when I try to call `vec` on other empty multisets.

**Comment by achim** [comment]
thanks for the report, fixed on master (thanks to @gfredericks). I'll publish new artifacts soon.
